"""new fields in user model

Revision ID: 08487e303c87
Revises: e5b65cbaf425
Create Date: 2022-04-21 20:05:03.040269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08487e303c87'
down_revision = 'e5b65cbaf425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
