"""empty message

Revision ID: 32b7e15c9105
Revises: 3feedefaeeeb
Create Date: 2022-05-24 23:06:49.795521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b7e15c9105'
down_revision = '3feedefaeeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.String(length=10), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    op.drop_column('user', 'state')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
